version: "3.5"
services:
  chronograf:
    image: chronograf:1.5.0.1-alpine
    hostname: chronograf
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    # ports:
    #   - "8888:8888"
    volumes:
      - "/var/docker/chronograf/data:/var/lib/chronograf"
    networks:
      - online
networks:
  online:
    external: true
    name: online
